### ISSUE TITLE
crash during PhysicsCollisionObject_finalizeNative

### ISSUE THREAD

**Issue by ertugrulcetin** [stephengold/Minie#12]
I'm using jme 3.3.2-stable and Minie 3.0.0. Here is the whole error: https://gist.github.com/ertugrulcetin/18559a3db0895bc62f07600df08412e3

Also, I used Minie `3.0.0+debug` got this error: https://gist.github.com/ertugrulcetin/b5d97540fca168b24464d9071a7441dd

**Comment by stephengold** [comment]
Thanks for the debug crash log ... that's helpful!

To self: `findLinearSearch()` on the world's collision-object array caused a segmentation violation. Was the world in some inconsistent state?

**Comment by ertugrulcetin** [comment]
Could be, I was using [re-init fn in here](https://github.com/ertugrulcetin/jme-clj/blob/test/fps-game/src/jme_clj/core.clj#L1006) (several times in a row). Maybe  I'm doing something wrong. The goal is to re-initialize the app without restarting it.

**Comment by stephengold** [comment]
Sorry, I don't understand Clojure yet. I've been studying the C++ code to figure out how an inconsistency might've arisen. No clarity yet. I may build a modified library and ask you to re-test...

**Comment by ertugrulcetin** [comment]
Sure, I'll re-test it. From my understanding, whatever we do in Java, Clojure in any other JVM language that uses jMonkeyEngine this crash should not happen right? It's the C++ code that has the problem? Or user code?

**Comment by stephengold** [comment]
I'm convinced this is a Minie bug, not a bug in JME or your application. It's likely you can work around it by clearing out physics spaces before they get GC'ed, but Minie shouldn't require that.

I expect the ultimate fix will probably involve changes to Minie's native libraries.

**Comment by ertugrulcetin** [comment]
Also, I get JVM crash on `bullet` and `bullet-native` deps too. (That's why I switched to Minie in the first place)

**Comment by ertugrulcetin** [comment]
@stephengold is there any update? Also, is there anything that I can help with? (testing, Java-related stuff). Sorry, I don't know C++ :(

**Comment by stephengold** [comment]
I've been busy with other bugs. If you could provide a simple Java app to trigger the crash, that might be very helpful.

**Comment by stephengold** [comment]
The new "Minie-3.1.0-test4" build incorporates a possible workaround for this issue. Try it and let me know whether (or not) it makes any difference for your application.

**Comment by ertugrulcetin** [comment]
Sure, will try ASAP.

**Comment by ertugrulcetin** [comment]
@stephengold I was going to write manual clearing physics space worked, but it failed last minute. Here is the JVM crash log: https://gist.github.com/ertugrulcetin/a28089705073b17cbf51137a2bba3ca1 it took longer compared to previous crashes.
jmonkey version: `3.3.2-stable`, Minie version: `3.1.0-test4`

In [clear function](https://github.com/ertugrulcetin/jme-clj/blob/move-bullet-to-minie/src/jme_clj/core.clj#L1014), those are the steps:
- Detach all children from rootNode
- Clear all lights from rootNode
- Get all states from **stateManager** using `getStates` method (reflection) and call `.detach` method, exclude these AppStates: `AudioListenerState, DebugKeysAppState, FlyCamAppState, ResetStatsState, StatsAppState`
   - If BulletApp state then call `clear-physics`
- invoke `terminatePending` method from  **stateManager** (reflection)
- call `simpleInitApp` method

**Comment by ertugrulcetin** [comment]
UPDATE: False alarm. It turns out I forgot to add manual clear fn to some other part that required it. It works, thanks! 

It does not work if I don't clear physics spaces manually tho.

**Comment by stephengold** [comment]
By commenting out the `physicsSpace.destroy()` in "TestIssue13.java" I am reproduced this issue on my Linux system. Therefore, this issue is not OSX-specific.

**Comment by stephengold** [comment]
I have a possible fix: https://github.com/stephengold/Libbulletjme/commit/489383e8993a4e03b66757ee9054ccec55e8fefc

**Comment by ertugrulcetin** [comment]
Once you release a test version, I can test it on my machine.

**Comment by stephengold** [comment]
The new "Minie-3.1.0" build incorporates the (proposed) fix. Try it and let me know whether (or not) it makes any difference for your application.

**Comment by ertugrulcetin** [comment]
Seems like it's fixed! Thank you so much, good job!
