### ISSUE TITLE
Must this be used with jMonkeyEngine?

### ISSUE THREAD

**Issue by orange451** [stephengold/Minie#25]
Hello,

I am a developer that sometimes writes my own little projects using OpenGL. However, I do not use jMonkey. Is it possible to use this library for physics without using jMonkey?

**Comment by stephengold** [comment]
@orange451 Minie can only be used with JMonkeyEngine. However, there's a subset of Minie in the Libbulletjme project, which doesn't depend on any library or engine. Probably that will meet your needs:  https://github.com/stephengold/Libbulletjme

**Comment by stephengold** [comment]
@orange451: Was my answer helpful to you?

**Comment by stephengold** [comment]
People!

**Comment by orange451** [comment]
I haven’t yet tried, but it looks like it will be great!
