### ISSUE TITLE
Gradle: Problems with '+' sign in version number 

### ISSUE THREAD

**Issue by Scrappers-glitch** [stephengold/Minie#26]
I have tested the new `Minie-4.9.0+bare` and `Minie-4.9.0+ano` parts of Minie library on android, and i found out that the bare part always replaces the ano part if both are added as dependencies, i suspect the problem comes from using '+' sign in declaring minie parts, in which gradle consumes it as a different version of minie, so a suggestion for the next release and for an eventual fix is to omit the '+' sign from minie parts and replace it by `library-module:version` classical way of defining library parts.

So, this is better : 
```java
implementation "com.github.stephengold:Minie-bare:5.x.x"
implementation "com.github.stephengold:Minie-ano:5.x.x"
```
instead of this : 
```java
implementation "com.github.stephengold:Minie:5.x.x+bare"
implementation "com.github.stephengold:Minie:5.x.x+bare"
```

By doing this, you are actually creating different `artificatId` names under the hood under the same library.

**Comment by stephengold** [comment]
The renaming can take place with the next release.

1. Have you verified that this issue occurs with more recent versions of Gradle, such as 6.9.2?
2. Have you verified that renaming one of the libraries solves the issue?

**Comment by Scrappers-glitch** [comment]
1. The issue (and the warning against the usage of '+" sign in version number) persists with gradle-6.9.2 and gradle-7.0.
2. The problem is with the part version makes it invalid, its not with the lib name, the issue is resolved when using : 
```java
implementation 'com.github.stephengold:Minie:4.9.0'
```
OR when adding the contents or `Minie+ano` manually in the android lib folder.

**Comment by Scrappers-glitch** [comment]
If you want to separate android natives from Minie, then you shouldn't use the '+' sign in version numbers, gradle will anticipate this as different versions of a same thing (which is not the case), instead it's better for new Minie versions to use a different modular expression with a dash `Minie-bare:5.x.x` and `Minie-ano:5.x.x`.

**Comment by stephengold** [comment]
For Minie v5, I've created an Android-only version of the library (Minie-5.0.0+droid) that includes both the java classes and the native libraries. As the name suggests, this is just version of Minie-5.0.0 that's specifically for Android projects. That should solve this issue.

@Scrappers-glitch please verify so I can close this issue.

**Comment by stephengold** [comment]
No response after a month, so I'll assume the solution is satisfactory.

**Comment by Scrappers-glitch** [comment]
> No response after a month, so I'll assume the solution is satisfactory.

Hello @sgold, sorry for very late reply, I was very busy those last two months, besides cleaning out my notifications that got cluttered up, I haven't tested these changes yet on android to assure the issue is resolved, but we can just keep this closed for now, I will be back on jme the next month or so and i will use Minie on android, so if something happens about this issue, we can reopen it...thanks for the update !
