### ISSUE TITLE
Character fall through ground in HelloWalkOtoCc test

### ISSUE THREAD

**Issue by Ali-RS** [stephengold/Minie#28]
Hi @stephengold 

When running HelloWalkOtoCc test the character fall through the terrain. I am using the master branch (cloned today).

Can you please confirm if it works fine for you?

OS: Linux Mint 20.1
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

**Comment by stephengold** [comment]
I can confirm HelloWalkOtoCc is broken and has been for a while. I'm investigating now.

**Comment by stephengold** [comment]
I found the bug. There was an uninitialized field in the app itself.

Solved in "master" branch at https://github.com/stephengold/Minie/commit/758e84a49bd63ee92db0d800dc9ebeef5b86fbc7

Thank you for bringing this issue to my attention.
