### ISSUE TITLE
Page not found for 'Collision Detection' link in README file

### ISSUE THREAD

**Issue by capdevon** [stephengold/Minie#29]
Hi Stephen, 
the `https://stephengold.github.io/Minie/minie/minie-library-tutorials/detect.html` link (Collision Detection), in the [tutorials](https://github.com/stephengold/Minie#tutorials)  section of the README file is broken.

Can you verify please? 

The error message is as follows:
```
Page Not Found
The page you’re looking for does not exist. It may have been moved.

If you arrived on this page by clicking on a link, please notify the owner of the site that the link is broken. 
If you typed the URL of this page manually, please double check that you entered the address correctly.
```
I hope I was helpful.

**Comment by stephengold** [comment]
Resolved at 32da925fd0e2694078cc05453f7e54feed98dadb.

Thank you, @capdevon!
