### ISSUE TITLE
Bug of PreComposer 

### ISSUE THREAD

**Issue by foxcc2021** [stephengold/Minie#30]
Hi, I found that there may be bugs in the version 5.1.0

"armature.getJointCount();" causes NPE in PreComposer when I remove DynamicAnimControl . (the "removeSpatialData" method in DacLinks will set the armature to null)

Another, PreComposer is created in "createSpatialData" but seems never removed in "removeSpatialData".
So when I add and remove DynamicAnimControl multiple times, there may be more than one PreComposer in the spatial.

Hope this helps.
![20220824191130](https://user-images.githubusercontent.com/93635496/186406945-ebb9311a-309d-4819-9351-517ce78b760f.jpg)

**Comment by stephengold** [comment]
Thank you for bringing these issues to my attention.

**Comment by stephengold** [comment]
@focc2021, I believe the new v6.0.0 release solve these issues. Could you verify the fix, please?

**Comment by foxcc2021** [comment]
I have tested version 6.0.0 and related issues have been fixed。

**Comment by stephengold** [comment]
@foxcc2021 Thank you for that confirmation.
