### ISSUE TITLE
Downloading two versions of the same jme3-testdata library

### ISSUE THREAD

**Issue by capdevon** [stephengold/Minie#38]
Hi @stephengold , 
is it correct that `Minie` downloads both `jme3-testadata-3.1.0` and `jme3-testadata-3.6.1` which are about 90 + 358 MB? 

Would it be correct to download only the latest version of the library when building the project with `Gradle`?

Here are the files that specify the two different versions of the library:
[Jme3Examples: jme3-testadata-3.6.1](https://github.com/stephengold/Minie/blob/master/Jme3Examples/build.gradle#L15)

[Minie-master: jme3-testadata-3.1.0](https://github.com/stephengold/Minie/blob/master/build.gradle#L22)

**Comment by stephengold** [comment]
Both releases of jme3-testdata are used, but in different contexts.

The 3.1.0 release of jme3-testdata includes the BaseMesh model, but no models with the new animation system. 3.1.0 is used during automated testing of the library and also while running applications in the MinieAssets, MinieExamples, and TutorialApps sub-projects. In particular, 5 apps in MinieExamples use BaseMesh, so I'm unwilling to abandon the 3.1.0 release.

The latest release of jme3-testdata (currently 3.6.1) includes models with the new animation system, but not the BaseMesh model. It is used while running applications in the Jme3Examples sub-project. At least 4 apps in Jme3Examples expect models with the new animation system.

There are other differences between the 3.1.0 and 3.6.1 versions of jme3-testdata, but I'm unsure whether they matter to Minie or not. The bottom line is that the project needs both versions.

**Comment by capdevon** [comment]
Thanks for the clarification. Since it's not a defect I'm closing the issue
