### ISSUE TITLE
Armature assigned but no weights elements cause IllegalStateException

### ISSUE THREAD

**Issue by oxplay2** [stephengold/Minie#5]
Hello, one issue was most annoy for me, because just without DAC, JME 3.3 animations were working properly. When add DAC where Armature have assigned geometries, but this geometries have no weights, it cause issue:

> mar 14, 2020 9:56:14 AM com.jme3.app.LegacyApplication handleError
> SEVERE: Uncaught exception thrown in Thread[main,5,main]
> java.lang.IllegalStateException: Max weights per vert is incorrectly set!
> 	at com.jme3.anim.SkinningControl.applySkinning(SkinningControl.java:464)
> 	at com.jme3.anim.SkinningControl.softwareSkinUpdate(SkinningControl.java:446)
> 	at com.jme3.anim.SkinningControl.controlRenderSoftware(SkinningControl.java:263)
> 	at com.jme3.anim.SkinningControl.controlRender(SkinningControl.java:303)
> 	at com.jme3.scene.control.AbstractControl.render(AbstractControl.java:118)
> 	at com.jme3.scene.Spatial.runControlRender(Spatial.java:757)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:721)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderSubScene(RenderManager.java:731)
> 	at com.jme3.renderer.RenderManager.renderScene(RenderManager.java:710)
> 	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1096)
> 	at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
> 	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:270)
> 	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:503)
> 	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:585)
> 	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:427)
> 	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
> 	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
> 	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
> 	at test.TestCharacterAnimationAndshader.main(TestCharacterAnimationAndshader.java:48)

here is example code that cause issue when using DAC control:

```
        Spatial body = ((Node) app.getAssetManager().loadModel("Models/game/character/body/body.gltf"));
        Spatial hair = ((Node) app.getAssetManager().loadModel("Models/game/character/hair/hair.gltf"));
        Spatial clothes = ((Node) app.getAssetManager().loadModel("Models/game/character/clothes/clothes.gltf"));
        Node model = new Node();
        model.attachChild(body);
        SceneGraphVisitor visitor = new SceneGraphVisitor() {
            @Override
            public void visit(Spatial spatTraversal) {
                if(!spatTraversal.getName().equals("Armature")){
                    ((Node)model.getChild("Armature")).attachChild(spatTraversal);
                }
            }
        };
        ((Node)hair).breadthFirstTraversal(visitor);
        ((Node)clothes).breadthFirstTraversal(visitor);

```

when i comment breadthFirstTraversal lines, it works. With them it dont because it looks like hairs/clothes i have no weights, but JME 3.3 animations skip them and work properly, while DAC throw issue.

I think DAC should skip no weights element, same as JME 3.3 animations do :)

**Comment by stephengold** [comment]
Thanks for reporting this issue.

**Comment by stephengold** [comment]
I did a quick test with a non-animated `Geometry` as a child of a `Node` with 3 controls (`AnimComposer`, DAC, and Skinning) and didn't see a crash. So apparently I don't understand the conditions that cause the crash you saw.

I'm unclear what you mean by "no weights elements". Clarify, please?

I'm also unclear where the DAC is added to the scene. Please provide a dump of the scene graph just prior to the crash, using `PhysicsDumper`:
```
    new PhysicsDumper().dump(rootNode);
```

**Comment by stephengold** [comment]
How might I re-create this issue?

**Comment by oxplay2** [comment]
it happened, when i tried apply skeleton models, that was exported using GLTF without skeleton(just with vertex weights)

Please note its additional model put into skeleton, not the only one.

but seems like wertex weights are not exported when there is not skeleton exported along with exported models.

here differences:

![image](https://user-images.githubusercontent.com/45903579/77230118-44175b00-6b92-11ea-80d2-3c5dc2bd0ce6.png)

![image](https://user-images.githubusercontent.com/45903579/77230110-382b9900-6b92-11ea-8eef-b129f67d1507.png)

But fact is that JME animations Work fine, with no bone weights. 

When i just add DAC, it throw error:

> mar 21, 2020 4:36:59 PM com.jme3.app.LegacyApplication handleError
> SEVERE: Uncaught exception thrown in Thread[main,5,main]
> java.lang.IllegalStateException: Max weights per vert is incorrectly set!

Please note its not same error when bone have no weights assigned, but when one of geoms have no weights assignes to bone.

> Early on, I tried creating links with zero vertices, but there were many issues.
> 
> If a BoneLink has no vertices, what should its shape be? Where would its center be? What would its mass be? What would its rotational inertia be? Minie would need to add a bunch of new interfaces to deal with such links.

so in this case, for this error, it could work, because there are "body" model weights assigned, just second model have no assignes, but is under skeleton control.

So since 3.3 Animation works (just dont move no weights model) i thoguht DAC should just also skip it.

**Comment by oxplay2** [comment]
so here example code:

```
    public void onGenerate() {
        Spatial body = ((Node) app.getAssetManager().loadModel("Models/game/character/woman/body/body.gltf"));
        Spatial hair = ((Node) app.getAssetManager().loadModel("Models/game/character/woman/hair/hair.gltf"));
        Spatial clothes = ((Node) app.getAssetManager().loadModel("Models/game/character/woman/clothes/clothes.gltf"));
        Node model = new Node();
        model.attachChild(body);
        SceneGraphVisitor visitor = new SceneGraphVisitor() {
            @Override
            public void visit(Spatial spatTraversal) {
                if(!spatTraversal.getName().equals("Armature")){
                    ((Node)model.getChild("Armature")).attachChild(spatTraversal);
                }
            }
        };
        //((Node)hair).breadthFirstTraversal(visitor);
        ((Node)clothes).breadthFirstTraversal(visitor);
        System.out.println("MORPH HELPER:" + model.getName());
        AnimMigrationUtils.migrate(model);
        node.attachChild(model);
    }
```

so since gody.gltf have weights, but clothes.gltf have no weights, it throw error when using DAC, while 3.3 animations just skip clothes and anim only body.gltf without error.

**Comment by stephengold** [comment]
If the bug is in Minie, why is the exception thrown in `SkinningControl` (in jme3-core)?

Perhaps the bug is actually in `SkinningControl`, but it only occurs when hardware skinning is disabled. Hardware skinning is enabled by default in 3.3, but `DynamicAnimControl` disables it.

Since I don't have access to your model, please re-test with `skinningControl.setHardwareSkinningPreferred(false)` and no `DynamicAnimControl`.

**Comment by oxplay2** [comment]
im not quite sure why.

but this only happened when DAC control was added.

**Comment by stephengold** [comment]
@oxplay2 Did you test with `skinningControl.setHardwareSkinningPreferred(false)`?

**Comment by oxplay2** [comment]
i cant check just now, because i have broken armature due to rootBone we talk about, once solved i will check it.

**Comment by stephengold** [comment]
I meant, test `skinningControl.setHardwareSkinningPreferred(false)` *without* adding a DAC.

**Comment by oxplay2** [comment]
setting (before creating and adding DAC control):

((Node)spatial).getChild("Armature").getControl(SkinningControl.class).setHardwareSkinningPreferred(false);

dont help, same issue.

**Comment by oxplay2** [comment]
Yes you are correct.

This cause issue, even without DAC. (when using no weight geoms)

so its JME issue trully, but DAC force it to "false" as i understand.

So its more like JME behave differently with this options set false/true, so its JME side.

**Comment by stephengold** [comment]
I understand why you attributed the crash to Minie. That was a plausible assumption.

`DynamicAnimControl` won't work with hardware skinning anytime soon. Perhaps we can get the underlying issue (in SkinningControl) resolved at the JMonkeyEngine project.

**Comment by stephengold** [comment]
See [IllegalStateException from software skinning with zero weights per vertex](https://github.com/jMonkeyEngine/jmonkeyengine/issues/1309).
