### ISSUE TITLE
Minie for jme 3.3

### ISSUE THREAD

**Issue by d01010101** [stephengold/Minie#6]
Is it possible to have Minie in 3.3. beta? I tried the following:

MonkeyEngine SDK 3.3.0-v3.3.0-beta1-sdk1-SNAPSHOT Java: 11.0.6; OpenJDK 64-Bit Server VM 11.0.6+10
I cloned Minie 14xfor33, possibly I should have tried root anyway. Then I followed the instructions until it turned out that there is nothing in Minie/subprojects. I tried to build Minie anyway:

JAVA_HOME="/home/local/jmonkeyplatform/jdk"
cd /home/local/Minie; ./gradlew --configure-on-demand -x check clean build
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script '/home/local/Minie/MinieLibrary/build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':MinieLibrary'.
> Could not set unknown property 'archiveBaseName' for task ':MinieLibrary:jar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s

**Comment by d01010101** [comment]
I tried root, but the effect is similar:

JAVA_HOME="/home/local/jmonkeyplatform/jdk"
cd /home/local/Minie_; ./gradlew --configure-on-demand -x check clean build
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script '/home/local/Minie_/MinieLibrary/build.gradle' line: 76

* What went wrong:
A problem occurred evaluating project ':MinieLibrary'.
> Could not set unknown property 'archiveBaseName' for task ':MinieLibrary:jar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s

**Comment by stephengold** [comment]
For the past year or so, every Minie release has been double, one version for JME 3.2 and another for JME 3.3. There are plenty of pre-built versions at GitHub and JCenter that work with JME 3.3, if that's all you need.

The build instructions in the README.md have always been for the JME 3.2 version, but the same instructions should work for JME 3.3, provided you replace "for32" with "for33".

Effective with the Minie 1.6 release (which might happen today/Sunday in my UTC-0700 timezone) JME 3.3 will be the default, which should reduce confusion somewhat.

The 14xfor33 branch was specifically for the Minie 1.4.1 patch release, which is now out of date. However, the usual build procedure should work there:
```text
    git clone https://github.com/stephengold/Minie.git
    cd Minie
    git checkout -b 14xfor33
    ./gradlew build
```

I haven't tested with `--configure-on-demand`, so perhaps that's what broke your build.

**Comment by d01010101** [comment]
I followed the build instruction for IDE, without the step of updating te plugins, as it did not work, but it was a fresh install of JME 3.3.

Otherwise, the build in CLI, outside IDE, works without problems, but this will mean that I will still need to integrate it with JME 3.3.

**Comment by stephengold** [comment]
The current instructions tell you to use a JME 3.2 SDK:
```
 + The setup instructions in this section are for jMonkeyEngine 3.2 SDKs
   (which are based on the NetBeans 8 IDE)
   and aren't expected to work with jMonkeyEngine 3.3 SDKs
   (which are based on the NetBeans 11 IDE).
 + It's easy to develop jMonkeyEngine 3.3 applications on a
   jMonkeyEngine 3.2 SDK, provided you use Gradle instead of Ant.
 + If you already have a jMonkeyEngine 3.2 SDK installed, skip to step 6.

The hardware and software requirements of the IDE are documented at
[the jMonkeyEngine wiki](https://jmonkeyengine.github.io/wiki/jme3/requirements.html).

 1. Download a jMonkeyEngine 3.2 Software Development Kit (SDK) from
    [GitHub](https://github.com/jMonkeyEngine/sdk/releases).
```

How could the documentation be any clearer?

We're in the midst of a transition right now, where the 3.3 Engine has been released, but the 3.3 is still in Beta Test and rather buggy. My advice would be not to use the 3.3 SDK for developing games.

**Comment by d01010101** [comment]
Yes I know that I did what is likely unsupported, but I risked because of a bug in the native bullet support in JME 3.2. Then I found out that the API in JME does not have the features I needed anyway so I can go back now to JME 3.2 without native bullet at all and try Minie instead. Thanks for the advice.

**Comment by stephengold** [comment]
Use the GitHub issue tracker only when you believe you've found a bug or issue in the software or its documentation. If you're unsure how to do something, or if you need troubleshooting help, use the JMonkeyEngine forums or send me a private message.
